# Generated by Django 5.0 on 2024-01-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_customuser_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='destrict',
            new_name='district',
        ),
    ]
